### ISSUE TITLE
ethernal listen causes TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by aspiers** [antoinedc/ethernal-cli#19]
Excited to try out Ethernal for the first time! I created an account and workspace, however `ethernal listen` crashes:

```
$ ethernal listen

Start listening for transactions

Options:
      --help       Show help                                           [boolean]
      --version    Show version number                                 [boolean]
  -w, --workspace  Workspace to connect to.                             [string]
  -d, --dir        Project directory to watch                            [array]
  -s, --server     Do not watch for artifacts change - only listen for
                   transactions
  -l, --local      Do not listen for transactions - only watch contracts

TypeError: Cannot read property 'get' of undefined
    at getDefaultWorkspace (/home/adam/.nvm/versions/node/v14.17.0/lib/node_modules/ethernal/bin/index.js:389:69)
    at async setWorkspace (/home/adam/.nvm/versions/node/v14.17.0/lib/node_modules/ethernal/bin/index.js:405:28)
    at async setupWorkspace (/home/adam/.nvm/versions/node/v14.17.0/lib/node_modules/ethernal/bin/index.js:418:5)
    at async Object.listen [as handler] (/home/adam/.nvm/versions/node/v14.17.0/lib/node_modules/ethernal/bin/index.js:422:5)
```

I added some debug and saw that `currentUser.data()` returns:

```
currentUser.data() is {
  plan: 'free',
  apiKey: '<censored>',
  stripeCustomerId: 'cus_<censored>'
}
```

but the code implies it should be returning an object which has a `currentWorkspace` property.  Seems that probably comes from the firebase db, so I guess it's a server-side issue?

**Comment by aspiers** [comment]
If I try `ethernal listen -w $my_workspace` it still doesn't work.  Debugging shows that

      currentWorkspace = await db.getWorkspace(options.workspace);

returns `undefined`.

**Comment by aspiers** [comment]
OK, logging out and in again restarted the onboarding wizard, after which it worked.  I suspect this was caused by me getting distracted half way through the onboarding wizard last time, so that somehow the workspace wasn't set up correctly.  But it's odd because I could see the workspace in the UI even before completing the wizard.

**Comment by antoinedc** [comment]
Your suspicion is correct :) it's failing when you start the CLI before creating a workspace.
I'll push a fix and I'll close this issue when it will be live, thanks for the report!
