### ISSUE TITLE
Cannot find module './common/helpers'

### ISSUE THREAD

**Issue by Mana-One** [antoinedc/ethernal-cli#20]
Hi, I've tried installing ethernal globally (and locally) in my project. However, whenever I try to use an ethernal command I get the error mentioned in the title.
For instance, when I type "ethernal -v", I get the following stack trace (using M1 Mac, node v16.13.2 and npm v8.1.2)
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './common/helpers'
Require stack:
- /usr/local/lib/node_modules/ethernal/node_modules/solc/linker.js
- /usr/local/lib/node_modules/ethernal/node_modules/solc/translate.js
- /usr/local/lib/node_modules/ethernal/node_modules/solc/wrapper.js
- /usr/local/lib/node_modules/ethernal/node_modules/solc/index.js
- /usr/local/lib/node_modules/ethernal/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethernal/node_modules/solc/linker.js:7:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ethernal/node_modules/solc/translate.js:5:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/ethernal/node_modules/solc/linker.js',
    '/usr/local/lib/node_modules/ethernal/node_modules/solc/translate.js',
    '/usr/local/lib/node_modules/ethernal/node_modules/solc/wrapper.js',
    '/usr/local/lib/node_modules/ethernal/node_modules/solc/index.js',
    '/usr/local/lib/node_modules/ethernal/bin/index.js'
  ]
}
```
Any ideas ? Thanks in advance.

**Comment by antoinedc** [comment]
Hi,

Thanks for reporting this! One of the package (solc) has a bug in the latest patch version (see: https://github.com/ethereum/solc-js/issues/624 for more details).

I've published an update that forces it to the latest stable version. So if you update to 0.13.1, you shouldn't have the issue anymore.

Let me know!

**Comment by Mana-One** [comment]
Hi,

Thanks for the quick answer ! It's all good, the cli works now, I'm having other errors but it's related to my config. Cheers.

**Comment by antoinedc** [comment]
Cool! Feel free to reach out on the Discord server if you need help with the setup!
