### ISSUE TITLE
Can't login or listen

### ISSUE THREAD

**Issue by ToJen** [antoinedc/ethernal-cli#22]
Ran `ethernal listen`. Same for `ethernal login`

Got
```bash
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@truffle/dashboard-message-bus-client'
Require stack:
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/dashboard.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/EventManager.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/config/dist/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/dashboard.js:4:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/index.js:3:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/dashboard.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/EventManager.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/config/dist/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/bin/index.js'
  ]
}
```

I tried doing a `npm i -g @truffle/dashboard-message-bus-client` and running `ethernal login` again but that produced this error:

```bash
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './messages'
Require stack:
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/node_modules/@truffle/dashboard-message-bus-common/dist/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/dist/client.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/dist/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/dashboard.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/EventManager.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/config/dist/index.js
- /Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/tomisinjenrola/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/node_modules/@truffle/dashboard-message-bus-common/dist/index.js:13:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/tomisinjenrola/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/dist/client.js:16:40)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/node_modules/@truffle/dashboard-message-bus-common/dist/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/dist/client.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/@truffle/dashboard-message-bus-client/dist/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/dashboard.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/defaultSubscribers/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/EventManager.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/node_modules/ethernal/node_modules/@truffle/events/index.js',
    '/Users/user/.nvm/versions/node/v16.15.0/lib/no...
```

**Comment by to-sh-1** [comment]
Same error message

**Comment by antoinedc** [comment]
Upgrading to 0.14.1 should fix this
